[package]
name = "devcode"
version = "0.1.0"
authors = ["crowlkats <13135287+crowlKats@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winit = "0.24.0"
wgpu = "0.7.1"
wgpu_glyph = "0.11.0"
anyhow = "1.0.40"
futures = "0.3.14"
shellexpand = "2.1.0"
bytemuck = { version = "1.5.1", features = [ "derive" ] }
unicode-segmentation = "1.7.1"
tree-sitter = "0.19.5"

[build-dependencies]
anyhow = "1.0.40"
cc = "1.0.68"
