[package]
name = "devcode"
version = "0.1.0"
authors = ["crowlkats <13135287+crowlKats@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winit = "0.24.0"
wgpu = "0.7.0"
wgpu_glyph = "0.11.0"
anyhow = "1.0.38"
futures = "0.3.13"
shellexpand = "2.1.0"
