name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  MONTSERRAT_URL: 'https://raw.githubusercontent.com/JulietaUla/Montserrat/master/fonts/ttf/Montserrat-Regular.ttf'

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            kind: lint
          - os: ubuntu-latest
            kind: debug
          - os: ubuntu-latest
            kind: release
          - os: macos-10.15
            kind: release
          - os: windows-2019
            kind: release

    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: install rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.50.0

    - name: install clippy and rustfmt
      if: matrix.kind == 'lint'
      run: |
        rustup component add clippy
        rustup component add rustfmt

    - name: lint
      if: matrix.kind == 'lint'
      run: cargo clippy -- -D clippy::all

    - name: check fmt
      if: matrix.kind == 'lint'
      run: cargo fmt -- --check

    - name: build debug
      if: matrix.kind == 'debug'
      run: cargo build --locked --all-targets

    - name: build release
      if: matrix.kind == 'release'
      run: cargo build --release --locked --all-targets -vv

    - name: upload release artifact
      if: matrix.kind == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: devcode_${{ matrix.os }}
        path: target/release/devcode*

    - name: install Montserrat (Ubuntu)
      if: (matrix.kind == 'debug' || matrix.kind == 'release') && startsWith(matrix.os, 'ubuntu')
      run: curl -o /usr/share/fonts/Montserrat-Regular.ttf $MONTSERRAT_URL

    - name: install Montserrat (Mac)
      if: (matrix.kind == 'debug' || matrix.kind == 'release') && startsWith(matrix.os, 'macos')
      run: curl -o /Library/Fonts/Montserrat-Regular.ttf $MONTSERRAT_URL

    - name: install Montserrat (Windows)
      if: (matrix.kind == 'debug' || matrix.kind == 'release') && startsWith(matrix.os, 'windows')
      run: |
        $client = new-object System.Net.WebClient
        $client.DownloadFile("$env:MONTSERRAT_URL", "C:\Windows\Fonts\Montserrat-Regular.ttf")

    - name: test debug
      if: matrix.kind == 'debug'
      run: cargo test --locked --all-targets -- --show-output

    - name: test release
      if: matrix.kind == 'release'
      run: cargo test --release --locked --all-targets -- --show-output
